grafana:
  adminUser: admin
  adminPassword: admin
  service:
    type: LoadBalancer
    port: 3000
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

prometheus:
  server:
    service:
      type: LoadBalancer
      port: 9090
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi
  alertmanager:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  kube-state-metrics:
    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
  nodeExporter:
    resources:
      requests:
        cpu: 20m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 64Mi
